### ISSUE TITLE
Bad utf8-encoded commit messages corrupt the import file

### ISSUE THREAD

**Issue by jbrichau** [peteruhnak/git-migration#11]
When converting the (legacy) Seaside30 Smalltalkhub repository to github, I encountered import errors which I traced to an incorrect declared byte size of the `data` command that carries the commit message text.

I also discovered that the class `GitMigrationCommitInfo` already has code to clean a commit message in `inlineDataFor:` but that is was unused. Changing the `writeCommitPreambleFor:` method such that it calls the `GitMigrationCommitInfo>>inlineDataFor:` method seems to fix the problem adequately.

I will prepare a PR after I check the result of migrating the Seaside30 repository with those changes.

**Comment by peteruhnak** [comment]
Hi, did you try in P6 or P7? I was doing some updates/fixes recently, but didn’t yet have time to backport everything for P6.

From: Johan Brichau
Sent: Thursday, July 19, 2018 7:12 PM
To: peteruhnak/git-migration
Cc: Subscribed
Subject: [peteruhnak/git-migration] Bad utf8-encoded commit messages corruptthe import file (#11)

When converting the (legacy) Seaside30 Smalltalkhub repository to github, I encountered import errors which I traced to an incorrect declared byte size of the data command that carries the commit message text.
I also discovered that the class GitMigrationCommitInfo already has code to clean a commit message in inlineDataFor: but that is was unused. Changing the writeCommitPreambleFor: method such that it calls the GitMigrationCommitInfo>>inlineDataFor: method seems to fix the problem adequately.
I will prepare a PR after I check the result of migrating the Seaside30 repository with those changes.

**Comment by jbrichau** [comment]
Hi Peter,

It was done in Pharo 7.
I did not check the Pharo 6 branch of gitmigration.

As far as I can tell, the migration for Seaside30 legacy worked fine: https://github.com/SeasideSt/Seaside-Legacy30 <https://github.com/SeasideSt/Seaside-Legacy30> but I need to check by loading it from the repo.
I also changed the `commitDate` with the `authoredDate` in this import, as it’s those original dates I want to see in the commit history.

Great work and really useful. I’ll make that PR asap.

**Comment by peteruhnak** [comment]
> Changing the writeCommitPreambleFor: method such that it calls the 
> GitMigrationCommitInfo>>inlineDataFor: method seems to fix the problem adequately.

Please note that this method should be removed. There is a subproject that is responsible for the actual writing and serialization https://github.com/peteruhnak/git-fast-writer

**Comment by peteruhnak** [comment]
I've made a change in the upstream project to correctly count utf content, so please give it another try (P7 fix only)

**Comment by jbrichau** [comment]
@peteruhnak I'm just back online after holidays and will check this week.

**Comment by peteruhnak** [comment]
I no longer maintain this project.

Please reopen any issues in the community-owned repo https://github.com/pharo-contributions/git-migration .
