### ISSUE TITLE
#isClassDefinition not found in OrderedCollection

### ISSUE THREAD

**Issue by georgeganea** [peteruhnak/git-migration#12]
I get this exception when trying to move the Cryptography (this is not the only one that triggers this error, it is just an example) repository to git.

<img width="1016" alt="screen shot 2018-09-25 at 10 23 56" src="https://user-images.githubusercontent.com/3874710/45999601-d1b5df80-c0ae-11e8-8155-1d5fe3fca6ad.png">
It happens when executing the last step.

`migration
	fastImportCodeToDirectory: 'Cryptography'
	initialCommit: '785682d219b2dfef1320ee6657211c74fb15ebf0'
	to: 'Cryptography.txt'.`

My entire script is:
`
migration := GitMigration on: 'http://www.squeaksource.com/Cryptography'.

migration downloadAllVersions.
migration populateCaches.

migration allAuthors.

newAuthors := OrderedCollection new.
migration allAuthors do: [ :each | 
	|email| email := '<',each,'>'.
	 newAuthors add: each -> {each . email} ].
newAuthors.
newAuthors add: ('GeorgeGanea' -> #('George Ganea' '<georgeganea@gmail.com>')).
migration authors: newAuthors.

migration
	fastImportCodeToDirectory: 'Cryptography'
	initialCommit: '785682d219b2dfef1320ee6657211c74fb15ebf0'
	to: 'Cryptography.txt'.
	`

This happens in 
Pharo 7.0
Build information: Pharo-7.0+alpha.build.1261.sha.9ed1473c3fb9c3853ee730e406bfb012c9fa8297 (32 Bit)
Is there anything else I could do to help with this issue?

**Comment by peteruhnak** [comment]
Thanks for the report!

This seems like a bug in Pharo/Tonel, I will look at it closer over this weekend and will let you know.

**Comment by georgeganea** [comment]
I was talking to @eliotmiranda about this and he wrote the following fix:
[TonelNoClassDefinitionsWhenWritingSnapshotFix.st.zip](https://github.com/peteruhnak/git-migration/files/2430732/TonelNoClassDefinitionsWhenWritingSnapshotFix.st.zip)
I guess I'll close this issue since the fix isn't in the git-migration tool.

**Comment by chisandrei** [comment]
Even with the above fix in my case it still fails in some cases when trying to migrate Glamour.

![error cannot determine package name from empty snapshot](https://user-images.githubusercontent.com/3534711/46436115-675d0900-c758-11e8-8608-cf52b9665704.png)

Seems that somehow a snapshot has an empty list of definitions.
@peteruhnak Any ideas if there is something that could be done in the migration tool?
If not is there something that could be fixed in Tonel?

**Comment by peteruhnak** [comment]
can you tell me the name of the broken MCZ? It seems strange that there's MCZ with no content... so TonelWriter is imho reacting correctly.

**Comment by chisandrei** [comment]
I get this error for more MCZ. Some are:

```
package name not found for a MCVersion(a MCVersionInfo(Glamour-Browsers-tg.1))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-Core-tg.3))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-Helpers-tg.1))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-Presentations-tg.1))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-Scripting-tg.1))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-Tests-tg.1))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-Squeak-tg.1))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.1))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.2))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.3))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.4))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.6))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-david_roethlisberger.7))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-david_roethlisberger.8))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-david_roethlisberger.9))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.10))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.11))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.12))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.13))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.14))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.15))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-tg.16))Error: cannot determine package name from empty snapshot
package name not found for a MCVersion(a MCVersionInfo(Glamour-All-jorge_ressia.17))Error: cannot determine package name from empty snapshot
```
