### ISSUE TITLE
Error in topologicallySort: when MCVersionInfo is incomplete

### ISSUE THREAD

**Issue by chisandrei** [peteruhnak/git-migration#13]
When migrating the GT repo (Moose/GToolkit) there is an `#hour was sent to nil` exception in #topologicallySort: as a MCVersionInfo has the `time` attribute nil.

![hour was sent to nil](https://user-images.githubusercontent.com/3534711/46467985-8480ee80-c7cf-11e8-961a-940608574885.png)
 
I can bypass this by setting a time of 00:00 but not sure why the time is not extracted from the mcz? Can it be missing? The MCVersionInfo looks kind of strange.

Anything that could be done in the migration tool?

**Comment by peteruhnak** [comment]
Can you tell me the full name of the MCZ?

**Comment by chisandrei** [comment]
The problem is I do not now it. The actual `MCVersionInfo` object does not contain any useful information.  But if in the debugger I go to `commitOrder` and inspect the `pkgVersions` list to which the MCZ belongs I get the following:

![mczlist](https://user-images.githubusercontent.com/3534711/46489680-579bfe00-c806-11e8-93a5-1396942c1d24.png)
