### ISSUE TITLE
Empty commit messages 

### ISSUE THREAD

**Issue by chisandrei** [peteruhnak/git-migration#14]
In Monticello there can be MCZs with an empty commit messages (at least I found some in the GT repo). Now they get imported in git to commits with an empty commit messages. This causes issues with some operations in git like rebase, which will fail if the git commit has an empty message. It can be fixed with something like the following on the git side:

```
git filter-branch -f --msg-filter '
read msg
if [ -n "$msg" ] ; then
    echo "$msg"
else
    echo "The commit message was empty"
fi'
```

But could be better to have a default template for missing commit messages (<The commit message was empty>).

**Comment by peteruhnak** [comment]
> But could be better to have a default template for missing commit messages ().
I had no idea that it would break tools, adding empty message template sounds like a plan. 👍

**Comment by chisandrei** [comment]
This is the problem that I run into: https://stackoverflow.com/questions/8542304/rebasing-a-git-history-with-empty-commit-messages

**Comment by peteruhnak** [comment]
I've introduced `onEmptyMessage:` (see docs)
