### ISSUE TITLE
Infinite loop when exporting in TonesWriter>>#splitMethodSource:

### ISSUE THREAD

**Issue by chisandrei** [peteruhnak/git-migration#17]
During the export of the history in Glamour there seems to be an infinite loop when exporting the mcz `Glamour-Examples-tg.36`. After half an hour the export made no progress. Interrupting the execution a few times always end up in `TonesWriter>>#splitMethodSource:` for the method  `a MCMethodDefinition(GLMSTNamedModel>>#nameØY)`. The strange part is that the selector name is `nameØY` while the source code of the method is:

```
named: aString
	^ self named: aString environment: self defaultEnvironment
```

![user interrupt](https://user-images.githubusercontent.com/3534711/46528621-8791e280-c894-11e8-9244-66f486a5f5be.png)

**Comment by peteruhnak** [comment]
This (and the other issue) sound like corrupted MCZs. Note that Pharo will by default read the binary snapshot in the mcz, not the source there (unless you remove the bin from the mcz).

 I will look in the evening in detail.

**Comment by peteruhnak** [comment]
This is indeed due to corrupted MCZ. Now GitMigration will avoid the loop and inform you (see updated docs).

I have also added `#ignoredFileNames:` so you can omit certain versions. 

e.g. here there are actually three corrupted versions

```smalltalk
migration ignoredFileNames: #('Glamour-Examples-tg.37' 'Glamour-Examples-tg.37' 'Glamour-Examples-tg.38').
```
