### ISSUE TITLE
GitMigrationMemoryTreeGitRepository>>#writeGitFileTreeProperties: does not exist

### ISSUE THREAD

**Issue by pdebruic** [peteruhnak/git-migration#19]
Its sent in GitMigrationMemoryTreeGitRepository>>#memoryStoreVersion:

Do you have a copy of the method lying around? 

thanks

**Comment by peteruhnak** [comment]
Can you please provide more info? I see the method in the code https://github.com/peteruhnak/git-migration/blob/6a4671537647795646e28043692b2d1732536d1b/repository/GitMigration/GitMigrationMemoryTreeGitRepository.class.st#L11

**Comment by pdebruic** [comment]
Are you showing me that #memoryStoreVersion: exists in your comment? 

In this issue I was pointing out that #writeGitFileTreeProperties: does not exist. 

Sorry for the delay!

**Comment by pdebruic** [comment]
Oh wait I didn't recognize that the fast writer project existed.  oops.

**Comment by pdebruic** [comment]
Oh wait that method 
GitMigrationMemoryTreeGitRepository>>#writeGitFileTreeProperties: is undefined in both projects but maybe never sent.

**Comment by peteruhnak** [comment]
Sorry, I no longer maintain this project.

Please reopen any issues in the community-owned repo https://github.com/pharo-contributions/git-migration .
