### ISSUE TITLE
Package Filter?

### ISSUE THREAD

**Issue by seandenigris** [peteruhnak/git-migration#9]
Is this currently possible? For example, I sometimes have an St repo with multiple tiny projects. When I'd like to port one to GH, I'd need to be able to specify a package filter (e.g. a block).

I hacked this behavior with:
```smalltalk
GitMigration>>versionsByPackage
	| versionsByPackage all |
	versionsByPackage := Dictionary new.
	all := repository versionsWithPackageNames.
	(all select: [ :e | e first beginsWith: 'Val' ])
		do: [ :quad | 
			(versionsByPackage at: quad first ifAbsentPut: [ OrderedCollection new ])
				add: (self cachedVersions at: (quad last withoutSuffix: '.mcz')) ].
	^ versionsByPackage
```

**Comment by peteruhnak** [comment]
This is currently not possible, feel free to send a PR.Otherwise I'll see
how I can incorporate it when I have a moment.

**Comment by peteruhnak** [comment]
I've introduced `selectedPackageNames:` (see docs)
